# Site settings
title: Yordi Verkroost # site title
description: >- # site description
  I do what I like and what gives me energy. I challenge myself. I help myself and others grow. Always with respect towards everyone and always independent.
lang: en-US # default lang
timezone: Europe/Amsterdam # set your timezone
image: assets/img/avatar_b.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/Froodooo/froodooo.github.io # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Yordi Verkroost # author name
  bio: >- # tell to the world
    I do what I like and what gives me energy. I challenge myself. I help myself and others grow. Always with respect towards everyone and always independent.
  username: froodooo # general username
  github: froodooo # github username
  twitter: yordiverkroost # twitter username
  email: info@yordiverkroost.com # email adress
  avatar: /assets/img/avatar_b.png # change with your own avatar

# URL settings
url: "https://yordi.me" #
baseurl: ""
permalink: /:title/
google_analytics: "G-337ZXJGN05"
fb_appid:

# Collection setting
collections:
  posts:
    output: true
  ask:
    output: true
    permalink: /:title

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-seo-tag
