# Site settings
title: yord.io # site title
description: >- # site description
  Living the Digital World
lang: en-US # default lang
timezone: Europe/Amsterdam # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/froodooo # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Yordi Verkroost # author name
  bio: >- # tell to the world
    Living the Digital World
  username: froodooo # general username
  github: froodooo # github username
  twitter: yordiverkroost # twitter username
  email: info@yordiverkroost.com # email adress
  avatar: /assets/img/avatar.png # change with your own avatar

# URL settings
url: "https://yord.io" #
baseurl: ""
permalink: /:title/
google_analytics: "UA-112081393-1"
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-admin
